version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - .:/web-app
    working_dir: /web-app/routes
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1