name: Deploy to Droplet

on:
  push:
    branches:
      - deployment 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -T -o StrictHostKeyChecking=no root@161.35.132.193 << 'EOF'
            echo hi
          EOF

