name: lint-ml-client
on:
  push:
    paths:
      - "machine-learning-client/**"
  pull_request:
    paths:
      - "machine-learning-client/**"

jobs:
  lint-and-format-ml:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install TensorFlow
        run: |
          cd machine-learning-client
          python -m pip install --upgrade pip
          pip install --no-cache-dir tensorflow-cpu>=2.16.0

      - name: Install Dependencies
        run: |
          cd machine-learning-client
          pip install --no-cache-dir -r requirements.txt

      - name: Lint with pylint
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          pylint **/*.py

      - name: Format with black
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          black --diff --check .
