name: lint-web-app
on:
  push:
    paths:
      - "web-app/**"
  pull_request:
    paths:
      - "web-app/**"

jobs:
  lint-and-format-web:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd web-app
          pip install --no-cache-dir -r requirements.txt

      - name: Lint with pylint
        if: ${{ hashFiles('web-app/**/*.py') != '' }}
        run: |
          cd web-app
          pylint **/*.py

      - name: Format with black
        if: ${{ hashFiles('web-app/**/*.py') != '' }}
        run: |
          cd web-app
          black --diff --check .
